# Generated by Django 4.2.7 on 2023-12-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittlelemonAPI', '0003_remove_menuitem_inventory_alter_category_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='price_after_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
